### ISSUE TITLE
Remove Hoek and import Topo directly to support older versions of Node.

### ISSUE THREAD

**Issue by rclayton-the-terrible** [the-terribles/evergreen#1]
```bash
npm test

> trbl-evergreen@0.0.1 test /home/ubuntu/evergreen
> mocha test


/home/ubuntu/evergreen/node_modules/topo/lib/index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/evergreen/lib/graph-builder.js:7:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/evergreen/lib/configurator.js:8:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/evergreen/test/configurator_spec.js:5:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /home/ubuntu/evergreen/node_modules/mocha/lib/mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/ubuntu/evergreen/node_modules/mocha/lib/mocha.js:216:14)
    at Mocha.run (/home/ubuntu/evergreen/node_modules/mocha/lib/mocha.js:468:10)
    at Object.<anonymous> (/home/ubuntu/evergreen/node_modules/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
npm ERR! Test failed.  See above for more details.

npm test returned exit code 1
```

**Comment by rclayton-the-terrible** [comment]
Nevermind; decided not to support any version of Node lower then 4.0.0 (which is the min supported by Hoek).
